import getImages from "@/common/imagesData";
import { TPortfolio, TUserProfile } from "../types";

export const portMock: TPortfolio = {
  investmentInfo: [
    {
      asset: {
        id: "1",
        title: "Digital Asset",
        logo: getImages("png1"),
        issueBy: "Issue By Digital Asset",
        image: getImages("example"),
        name: "THGG",
        description: "Blockchain Innovations Global (B.I.G.)",
        catagory: "Healthcare",
        return: "18%",
        region: "Asia",
        minimum: "250.00 USD",
      },
      info: {
        id: "1",
        totalIssuance: "1000.00 DA",
        totalAmountRaised: "50000.00 USD",
        contractInfomation: "0x0000000000000000000000000000000000000000",
        minimumInvestmentAmount: "1000.00 USD",
        minimumInvestmentQuantity: "100.00 DA",
        issueUnitPrice: "100.00 USD",
      },
      keyInformation: {
        id: "1",
        network: "BNB Smart Chain Mainnet",
        precision: "5",
        capitalStructure: "Independent Fund",
        classification: "Retail Investor",
        productType: "Others",
        creationTime: "2023-01-01T00:00:00Z",
        releaseTime: "2023-02-01T00:00:00Z",
        compleationTime: "2023-03-01T00:00:00Z",
      },
      issuanceTerms: {
        id: "1",
        investmentPeriod: "120 Days",
        dividendYield: "5%",
        grossmargin: "20%",
        equityMultiple: "5%",
        profit: "15%",
        leverage: "20%",
        investmentStructure: "/",
        distributionFrequency: "Quarterly",
      },
      icoStatus: "funding",
      investment: {
        id: "1",
        createAt: "2023-03-01T00:00:00Z", //invest date
        assetUid: "uuid",
        userId: "uuid",
        currrency: "THB",
        amount: "10000000",
        unit: "1000000",
        prices: "10",
      },
    },
    {
      asset: {
        id: "2",
        title: "Crypto Asset",
        logo: getImages("png2"),
        issueBy: "Issue By Crypto Asset",
        image: getImages("example2"),
        name: "BTCG",
        description: "Global Crypto Innovations",
        catagory: "Finance",
        return: "20%",
        region: "Europe",
        minimum: "500.00 USD",
      },
      info: {
        id: "2",
        totalIssuance: "2000.00 DA",
        totalAmountRaised: "100000.00 USD",
        contractInfomation: "0x1111111111111111111111111111111111111111",
        minimumInvestmentAmount: "2000.00 USD",
        minimumInvestmentQuantity: "200.00 DA",
        issueUnitPrice: "200.00 USD",
      },
      keyInformation: {
        id: "2",
        network: "Ethereum Mainnet",
        precision: "8",
        capitalStructure: "Private Fund",
        classification: "Institutional Investor",
        productType: "Equity",
        creationTime: "2023-02-01T00:00:00Z",
        releaseTime: "2023-03-01T00:00:00Z",
        compleationTime: "2023-04-01T00:00:00Z",
      },
      issuanceTerms: {
        id: "2",
        investmentPeriod: "180 Days",
        dividendYield: "6%",
        grossmargin: "25%",
        equityMultiple: "6%",
        profit: "18%",
        leverage: "25%",
        investmentStructure: "/",
        distributionFrequency: "Annually",
      },
      icoStatus: "live",
      investment: {
        id: "2",
        createAt: "2022-04-01T00:00:00Z", //invest date
        assetUid: "uuid2",
        userId: "uuid2",
        currrency: "USD",
        amount: "20000000",
        unit: "2000000",
        prices: "20",
      },
    },
    {
      asset: {
        id: "3",
        title: "Token Asset",
        logo: getImages("png3"),
        issueBy: "Issue By Token Asset",
        image: getImages("example3"),
        name: "ETHG",
        description: "Global Token Innovations",
        catagory: "Technology",
        return: "22%",
        region: "North America",
        minimum: "750.00 USD",
      },
      info: {
        id: "3",
        totalIssuance: "3000.00 DA",
        totalAmountRaised: "150000.00 USD",
        contractInfomation: "0x2222222222222222222222222222222222222222",
        minimumInvestmentAmount: "3000.00 USD",
        minimumInvestmentQuantity: "300.00 DA",
        issueUnitPrice: "300.00 USD",
      },
      keyInformation: {
        id: "3",
        network: "Avalanche Mainnet",
        precision: "6",
        capitalStructure: "Hedge Fund",
        classification: "Accredited Investor",
        productType: "Debt",
        creationTime: "2023-03-01T00:00:00Z",
        releaseTime: "2023-04-01T00:00:00Z",
        compleationTime: "2023-05-01T00:00:00Z",
      },
      issuanceTerms: {
        id: "3",
        investmentPeriod: "240 Days",
        dividendYield: "7%",
        grossmargin: "30%",
        equityMultiple: "7%",
        profit: "21%",
        leverage: "30%",
        investmentStructure: "/",
        distributionFrequency: "Monthly",
      },
      icoStatus: "cancle",
      investment: {
        id: "3",
        createAt: "2023-05-01T00:00:00Z", //invest date
        assetUid: "uuid3",
        userId: "uuid3",
        currrency: "EUR",
        amount: "30000000",
        unit: "3000000",
        prices: "30",
      },
    },
  ],
  accountBalance: {
    id: "1",
    userId: "uuid",
    currency: "THB",
    balance: "10000000",
    used: "9500000",
    available: "500000",
  },
};

export const userMock: TUserProfile = {
  accountId: "xx-xxx-xxx-xxx",
  email: "test@email.com",
  avatar: getImages("png1"),
  firstName: "moo",
  lastName: "dang",
};
