// import upIcons from "@assets/drawIcon/up.png";
// import whiteBg from "@assets/drawIcon/whiteBg.png";
import { TDataProps } from "../type";
import getImages from "@/common/imagesData";

export const dataForHot: TDataProps[] = [
  {
    id: "1",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Varaa",
    image: getImages("png1"),
    name: "THGG",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Others",
    return: "20%",
    region: "Global",
    minimum: "100.00 USD",
  },
  {
    id: "2",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Emma",
    image: getImages("png2"),
    name: "Global Vinum Investments",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Commodity",
    return: "10%",
    region: "Global",
    minimum: "100.00 USD",
  },
  {
    id: "3",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png3"),
    name: "贵族红酒庄园投资股权",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Bond",
    return: "6%",
    region: "Global",
    minimum: "1000.00 USD",
  },
];

export const dataForRecomended = [
  {
    id: "4",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Brand Co",
    image: getImages("whiteBg"),
    name: "TESTNG",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Real Estate",
    return: "15%",
    region: "Global",
    minimum: "1000.00 USD",
  },
  {
    id: "5",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Varaa",
    image: getImages("png1"),
    name: "THGG",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Others",
    return: "20%",
    region: "Global",
    minimum: "100.00 USD",
  },
  {
    id: "6",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By ABC",
    image: getImages("png4"),
    name: "Global Property Investments (GPI)",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Crytocurrency",
    return: "10%",
    region: "Global",
    minimum: "100.00 USD",
  },
];

export const dataAll: TDataProps[] = [
  {
    id: "7",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Brand Co",
    image: getImages("whiteBg"),
    name: "TESTNG",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Real Estate",
    return: "15%",
    region: "Global",
    minimum: "1000.00 USD",
  },
  {
    id: "8",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Varaa",
    image: getImages("png1"),
    name: "THGG",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Others",
    return: "20%",
    region: "Global",
    minimum: "100.00 USD",
  },
  {
    id: "9",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png4"),
    name: "Global Property Investments (GPI)",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Real Estate",
    return: "10%",
    region: "Global",
    minimum: "200.00 BRL",
  },
  {
    id: "10",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By ABC",
    image: getImages("png4"),
    name: "Global Property Investments (GPI)",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Crytocurrency",
    return: "10%",
    region: "Global",
    minimum: "100.00 USD",
  },
  {
    id: "11",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png5"),
    name: "Adipiscing Elit",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Bond",
    return: "5%",
    region: "Global",
    minimum: "200.00 USD",
  },
  {
    id: "12",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png3"),
    name: "国际房地产投资基金",
    description: "Blockchain Innovations Global (B.I.G)",
    catagory: "Fund",
    return: "5%",
    region: "Global",
    minimum: "500.00 USD",
  },
  {
    id: "13",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png6"),
    name: "Global Independent Fund",
    description: "Blockchain Innovations Global (B.I.G.)",
    catagory: "Fund",
    return: "4%",
    region: "Global",
    minimum: "200.00 USD",
  },
  {
    id: "14",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png8"),
    name: "国际房地产发展基金",
    description: "Blockchain Innovations Global (B.I.G.)",
    catagory: "Fund",
    return: "7%",
    region: "Global",
    minimum: "1000.00 USD",
  },
  {
    id: "15",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Bowen",
    image: getImages("png1"),
    name: "贵族红酒庄园投资股权",
    description: "Blockchain Innovations Global (B.I.G.)",
    catagory: "Bond",
    return: "6%",
    region: "Global",
    minimum: "1000.00 USD",
  },
  {
    id: "15",
    title: "Digital Asset",
    logo: getImages("logo"),
    issueBy: "Issue By Emma",
    image: getImages("png2"),
    name: "Global Vinum Investments",
    description: "Blockchain Innovations Global (B.I.G.)",
    catagory: "Commodity",
    return: "10%",
    region: "Global",
    minimum: "100.00 USD",
  },
];
